pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r app/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'python -m unittest discover'
            }
        }
        stage('Deploy') {
            steps {
                sh 'terraform -chdir=infrastructure/ apply -auto-approve'
            }
        }
    }
}
