apiVersion: v1
kind: Service
metadata:
  name: loan-rpa-app-service
spec:
  selector:
    app: loan-rpa-app
  ports:
    - protocol: TCP
      port: 80        # External port (LoadBalancer)
      targetPort: 5000 # Internal port (Flask app should use 5000)
  type: LoadBalancer