name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0 # Adjust to your required version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your desired AWS region

      - name: Validate Terraform files
        run: |
          cd infrastructure
          terraform validate

      - name: Debug SSH Public Key Length
        run: echo "SSH Public Key Length: ${#SSH_PUBLIC_KEY}"
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: List files in repository
        run: ls -la

      - name: List Terraform files
        run: ls -la infrastructure

      - name: Change directory to infrastructure and run Terraform
        run: |
          cd infrastructure
          terraform init

          # Enable debug logging
          export TF_LOG=DEBUG
          
          # Run terraform plan and capture output
          terraform plan -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -out=tfplan -input=false

          # Optionally display the plan output if needed
          terraform show tfplan

          # Apply the plan
          terraform apply -auto-approve tfplan




# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.3.0 # Adjust to your required version

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1  # Specify your desired AWS region

#       - name: List files in repository
#         run: ls -la

#       - name: List Terraform files
#         run: ls -la infrastructure

#       - name: Change directory to infrastructure and run Terraform
#         run: |
#           cd infrastructure
#           terraform init
          
#           # Run terraform plan and capture output
#           terraform plan -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -out=tfplan

#           # Optionally display the plan output if needed
#           terraform show tfplan

#           # Apply the plan
#           terraform apply -auto-approve tfplan