name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Adjust to your required version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your desired AWS region

      - name: Change directory to infrastructure and run Terraform
        run: |
          cd infrastructure
          terraform init
          terraform plan -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -out=tfplan
          terraform show tfplan
          terraform apply -auto-approve tfplan

  docker:
    runs-on: ubuntu-latest
    needs: terraform  # Ensure the terraform job is completed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t abigailnkole96/loan_rpa_app:latest .

      - name: Push Docker Image
        run: |
          docker push abigailnkole96/loan_rpa_app:latest

  kubernetes:
    runs-on: ubuntu-latest
    needs: docker  # Ensure the docker job is completed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory and list contents
        run: |
          pwd
          ls -la
          ls -la infrastructure

      - name: Change directory to infrastructure and apply Kubernetes deployment
        run: |
          cd infrastructure
          kubectl apply -f deployment.yaml