name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0 # Adjust to your required version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your desired AWS region

      - name: List files in repository
        run: ls -la

      - name: List Terraform files
        run: ls -la infrastructure

      - name: Change directory to infrastructure and run Terraform
        run: |
          cd infrastructure
          terraform init
          terraform plan -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          terraform apply -auto-approve -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
