name: CI/CD for Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the version you want to use

      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init

      - name: Terraform Validate
        working-directory: ./infrastructure
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}  # Pass the secret as an environment variable
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infrastructure
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}  # Pass the secret as an environment variable
        run: terraform plan -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"  # Pass the variable to Terraform

      - name: Terraform Apply
        working-directory: ./infrastructure
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}  # Pass the secret as an environment variable
        run: terraform apply -auto-approve -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"  # Pass the variable to Terraform
