name: Python Tests

on:
  push:
    branches:
      - main  # Or specify any branch you want the tests to run on
  pull_request:
    branches:
      - main  # Run tests on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner with Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the version of Python you want to use

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools==67.5.1 wheel  # Upgrade pip and pin setuptools

      - name: Install dependencies
        run: |
          pip install --prefer-binary -r requirements.txt  # Force pip to use binary packages

      - name: Run tests with pytest
        run: |
          pytest  # Run pytest to execute tests